import { spawn } from 'node:child_process';
import fs from 'node:fs/promises';
import { openSync } from 'node:fs';
import assert from 'node:assert/strict';
// Start the local Vite preview before running this test.
const chrome=spawn(process.env.CHROME_BIN || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-sandbox','--disable-gpu','--no-first-run','--disable-background-networking','--remote-debugging-port=9238','--user-data-dir=/tmp/coffee-backlog-cdp-v2','about:blank'],{stdio:['ignore','ignore',openSync('/tmp/backlog-chrome.log','w')],detached:true});
const pause=ms=>new Promise(r=>setTimeout(r,ms));
let ws;
try{
 let target;
 for(let i=0;i<200;i++){try{target=await (await fetch('http://127.0.0.1:9238/json/new?about:blank',{method:'PUT'})).json();break;}catch{await pause(100);}}
 if(!target)throw Error('Chrome did not start');
 ws=new WebSocket(target.webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
 let seq=0;const pending=new Map(),errors=[];
 ws.onmessage=event=>{const msg=JSON.parse(event.data);if(msg.id){const p=pending.get(msg.id);pending.delete(msg.id);msg.error?p.reject(Error(JSON.stringify(msg.error))):p.resolve(msg.result);}else if(msg.method==='Runtime.exceptionThrown')errors.push(msg.params.exceptionDetails.text+' '+msg.params.exceptionDetails.exception?.description);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const id=++seq;pending.set(id,{resolve,reject});ws.send(JSON.stringify({id,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,awaitPromise:true,returnByValue:true});if(r.exceptionDetails)throw Error(r.exceptionDetails.exception?.description||r.exceptionDetails.text);return r.result.value;};
 const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await pause(50);}throw Error('Timed out: '+expression);};
 const click=async selector=>{await evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);await pause(70);};
 const reset=async()=>{await evaluate('window.resetFixture()');await click('[data-stage="collecting"]');};
 const point=async selector=>evaluate(`(()=>{const e=document.querySelector(${JSON.stringify(selector)});const r=e.getBoundingClientRect();return {x:r.x+r.width/2,y:r.y+r.height/2};})()`);
 await send('Runtime.enable');await send('Page.enable');
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await send('Page.navigate',{url:'http://127.0.0.1:5173/tests/backlog-fixture.html'});
 await wait('!!window.controller');await reset();
 assert.equal(await evaluate('document.documentElement.scrollWidth'),390);
 assert.match(await evaluate('document.querySelector(".backlog-bucket-name").textContent'),/Plan v2/);
 await click('[data-action="add-child"][data-item="parent"]');
 await evaluate(`document.querySelector('#backlogEditor textarea').value='new subtask'; document.querySelector('#backlogEditor').requestSubmit()`);await wait('window.fixture.revision===2');
 assert.deepEqual(await evaluate('window.fixture.document.buckets[0].items.map(x=>[x.text,x.depth])'),[['parent',0],['child',1],['new subtask',1],['sibling',0]]);
 await click('[data-action="toggle-item"][data-item="child"]');
 assert.equal(await evaluate('document.querySelector("[data-action=toggle-item][data-item=parent]").indeterminate'),true);
 await click('[data-action="queue-item"][data-item="parent"]');
 assert.equal(await evaluate('window.fixture.document.buckets.find(b=>b.stage==="pending").items.length'),3);
 await click('[data-action="queue-bucket"][data-bucket="b"]');
 assert.equal(await evaluate('window.fixture.document.buckets.filter(b=>b.stage==="pending").length'),1);
 await click('[data-stage="pending"]');await click('[data-action="delete-item"][data-item="parent"]');await click('[data-action="confirm-delete"]');
 assert.deepEqual(await evaluate('window.fixture.document.buckets.find(b=>b.stage==="pending").items.map(i=>i.text)'),['other']);
 console.log('PASS mobile subtask, partial checkbox, quick queue, single batch and cascade delete');
 await reset();await click('[data-action="edit-item"][data-item="parent"]');
 await click('[data-action="choose-target"][data-value="b"]');
 await evaluate('document.querySelector("#backlogEditor").requestSubmit()');await wait('window.fixture.revision===2');
 assert.deepEqual(await evaluate('window.fixture.document.buckets.find(b=>b.id==="b").items.map(x=>[x.text,x.depth])'),[['other',0],['parent',0],['child',1]]);
 console.log('PASS editor moves full subtree');
 await reset();await click('[data-action="add-child"][data-item="parent"]');
 await evaluate(`window.failNext=true; const t=document.querySelector('#backlogEditor textarea');t.value='keep my draft';t.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#backlogEditor').requestSubmit()`);
 await pause(100);assert.equal(await evaluate('document.querySelector("#backlogEditor textarea").value'),'keep my draft');
 await click('[data-action="close-editor"]');
 console.log('PASS failed save preserves draft');
 await reset();
 await send('Emulation.setDeviceMetricsOverride',{width:1200,height:900,deviceScaleFactor:1,mobile:false});
 let start=await point('.backlog-drag-handle[data-item="parent"]'),end=await point('.backlog-bucket[data-bucket="b"] .backlog-bucket-head');
 await send('Input.dispatchMouseEvent',{type:'mousePressed',...start,button:'left',clickCount:1});
 await send('Input.dispatchMouseEvent',{type:'mouseMoved',x:start.x+10,y:start.y+5,button:'left',buttons:1});
 await send('Input.dispatchMouseEvent',{type:'mouseMoved',...end,button:'left',buttons:1});
 await send('Input.dispatchMouseEvent',{type:'mouseReleased',...end,button:'left',clickCount:1});
 await wait('window.fixture.revision===2');
 assert.deepEqual(await evaluate('window.fixture.document.buckets.find(b=>b.id==="b").items.map(x=>x.id)'),['other','parent','child']);
 console.log('PASS Mac mouse drag moves subtree across buckets');
 await pause(450);await reset();
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});
 await send('Emulation.setTouchEmulationEnabled',{enabled:true,maxTouchPoints:1});
 start=await point('.backlog-drag-handle[data-item="parent"]');end=await point('.backlog-bucket[data-bucket="b"] .backlog-bucket-head');
 await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...start,id:1}]});await pause(400);
 await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...end,id:1}]});
 await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait('window.fixture.revision===2');
 assert.deepEqual(await evaluate('window.fixture.document.buckets.find(b=>b.id==="b").items.map(x=>x.id)'),['other','parent','child']);
 console.log('PASS mobile hold-and-drag moves subtree across buckets');
 await pause(450);await reset();
 start=await point('.backlog-drag-handle[data-item="parent"]');end=await point('[data-stage="pending"]');
 await send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...start,id:2}]});await pause(400);
 await send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{...end,id:2}]});await pause(650);
 await send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});await wait('window.fixture.revision===2');
 assert.equal(await evaluate('window.fixture.document.buckets.find(b=>b.stage==="pending").items.length'),2);
 console.log('PASS touch drag through Pending stage creates the single batch');
 await pause(450);
 await evaluate(`window.fixture.document.buckets=[{id:'large',title:'Next batch',version:'',stage:'pending',items:Array.from({length:13},(_,i)=>({id:'work'+i,text:'Task '+i,done:false,note:false,depth:0}))}];window.fixture.revision++;window.controller.reload()`);
 await click('[data-stage="pending"]');
 assert.match(await evaluate('document.querySelector(".backlog-batch-warning").textContent'),/13 tasks/);
 assert.equal(await evaluate('document.documentElement.scrollWidth'),390);
 const shot=await send('Page.captureScreenshot',{format:'png'});await fs.writeFile('/tmp/coffee-backlog-v2-phone.png',Buffer.from(shot.data,'base64'));
 assert.deepEqual(errors,[]);console.log('PASS batch-size warning, phone width and no browser exceptions');
}finally{ws?.close();try{process.kill(-chrome.pid,'SIGTERM');}catch{}}
